baseURL = 'https://example.org/'
title = "Andrew's Selkouutiset Archive"
theme = 'minimum-viable-hugo'

DefaultContentLanguage = "fi"  
[languages]
  [languages.fi]
    languageName = "Suomi"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2

