baseURL = 'https://example.org/'
languageCode = 'fi'
title = "Andrew's Selkouutiset Archive"
theme = 'selkoarchive'

DefaultContentLanguage = "fi"

[languages]
  [languages.fi]
    title = "Andrew's Selkouutiset Archive"
    weight = 1
  [languages.en]
    title = "Andrew's Selkouutiset Archive"
    weight = 2
